lib/cf/broker/src/routes/bind-service.js, lib/cf/broker/src/routes/create-service.js, lib/cf/broker/src/test/bind-test.js, lib/cf/broker/src/test/create-test.js, lib/cf/broker/src/test/uaa-test.js
=> Service broker prefixes plan ids with resource provider.

lib/plugins/provisioning/src/test/plans-updating-test.js
Signed-off-by: Yulia Nedyalkova <yulia.nedyalkova@sap.com>
=> Refactor tests for plan update

lib/cf/broker/src/catalog/catalog.js, lib/cf/broker/src/test/catalog-test.js
Signed-off-by: Hristo Dobtchev <hristo.dobtchev@sap.com>
=> Support prefix of catalog ids

package.json
Signed-off-by: Yulia Nedyalkova <yulia.nedyalkova@sap.com>
=> Remove bootstrap npm script

lib/cf/broker/manifest.yml, lib/cf/broker/src/routes/create-service.js, lib/cf/broker/src/test/create-test.js
Signed-off-by: Hristo Dobtchev <hristo.dobtchev@sap.com>
=> Add dashboard url to service provisioning request

lib/cf/broker/manifest.yml, lib/cf/broker/src/auth/oauth.js, lib/cf/broker/src/auth/uaa.js, lib/cf/broker/src/config.js, lib/cf/broker/src/test/healthcheck-test.js, lib/cf/broker/src/test/oauth-test.js, lib/extensions/housekeeper/manifest.yml
Signed-off-by: Hristo Iliev <hsiliev@gmail.com>
=> Use API and AUTH_SERVER env.variables

test/provisioning/src/test/plans-acceptance-test.js
Signed-off-by: Hristo Iliev <hsiliev@gmail.com>
=> Change CF_API env.variable to API in itest

test/provisioning/src/test/plans-acceptance-test.js
=> Move debug logs after error check

lib/cf/broker/src/auth/oauth.js
Signed-off-by: Hristo Dobtchev <hristo.dobtchev@sap.com>
=> Fix debug message in oauth

lib/cf/broker/manifest.yml
Signed-off-by: Hristo Dobtchev <hristo.dobtchev@sap.com>
=> Fix sample manifest

lib/cf/broker/src/routes/create-service.js, lib/cf/broker/src/test/create-test.js
* Fixes #26 
Signed-off-by: Georgi Lozev <georgi.lozev@sap.com>
=> Improve error handling in creating plans and mappings

lib/extensions/healthchecker/.apprc, lib/extensions/healthchecker/.gitignore, lib/extensions/healthchecker/.npmrc, lib/extensions/healthchecker/README.md, lib/extensions/healthchecker/manifest.yml, lib/extensions/healthchecker/package.json, lib/extensions/healthchecker/src/index.js, lib/extensions/healthchecker/src/test/test.js
Signed-off-by: Nikolay Maslarski <nikolay.maslarski@sap.com>
=> Introduce healthchecker extension

etc/apps.rc, lib/cf/broker/npm-shrinkwrap.json, lib/extensions/healthchecker/npm-shrinkwrap.json, lib/extensions/housekeeper/npm-shrinkwrap.json
Signed-off-by: Stoyan Gradev <stoyan.gradev@sap.com>
=> Add missing shrinkwrap files: broker, healthcheck and hopusekeeper

test/provisioning/src/test/plans-acceptance-test.js, test/test-utils/src/index.js
=> Use new abacus-client in plans-acceptance-test

test/provisioning/src/test/plans-acceptance-test.js, test/test-utils/src/index.js
This reverts commit 7ae481031ab9fae934532e5183228f6351cae7bd.
=> Revert "Use new abacus-client in plans-acceptance-test (#59)"

test/provisioning/src/test/plans-acceptance-test.js, test/provisioning/src/test/utils/uaa-utils.js
Signed-off-by: Georgi Lozev <georgi.lozev@sap.com>
=> Accept 409 as expected behaviour in plans-acceptance-test

test/broker/src/test/broker-smoke-test.js
Signed-off-by: Georgi Lozev <georgi.lozev@sap.com>
=> Accept 409 as expected behaviour in broker-test

lib/cf/broker/npm-shrinkwrap.json, lib/cf/dashboard/npm-shrinkwrap.json, lib/extensions/healthchecker/npm-shrinkwrap.json, lib/extensions/housekeeper/npm-shrinkwrap.json, lib/plugins/account/npm-shrinkwrap.json, lib/plugins/provisioning/npm-shrinkwrap.json, npm-shrinkwrap.json, package.json
* Fix shrinkwrap
* Bump abacus
=> Fix shrinkwrap

lib/cf/dashboard/src/test/errormiddleware-test.js
- use sinon matcher instead to achieve the same result
=> Do not deep equal objects in dashboard test

lib/cf/dashboard/.apprc, lib/cf/dashboard/.cfignore, lib/cf/dashboard/manifest.yml, lib/cf/dashboard/npm-shrinkwrap.json, lib/cf/dashboard/package.json, lib/cf/dashboard/src/application.js, lib/cf/dashboard/src/config.js, lib/cf/dashboard/src/controllers/CfApiController.js, lib/cf/dashboard/src/db/DbController.js, lib/cf/dashboard/src/db/index.js, lib/cf/dashboard/src/routes/ui.js, lib/cf/dashboard/src/test/dbcontroller-test.js, lib/cf/dashboard/src/test/lib/index.js, lib/cf/dashboard/src/test/lib/test_settings.json, lib/cf/dashboard/src/test/routes-test.js, lib/cf/dashboard/src/test/uiroute-test.js, package.json
- Implement persistent sessions with support for Mongo + Couch
- Allow pure scalability for dashboard
=> Make Dashboard Sessions Non-Sticky

lib/cf/broker/src/test/create-test.js
=> Fix dashboard url unit test

lib/cf/broker/src/routes/create-service.js, lib/cf/broker/src/test/config-test.js, lib/cf/broker/src/test/create-test.js
=> Initial version of create service with custom plans

lib/cf/broker/src/routes/create-service.js
=> Add create service debug messages

test/broker/src/test/broker-smoke-test.js
Signed-off-by: Vasil Petkov <v.petkov@sap.com>
=> Improve broker smoke test

tools/cmdline/src/cf-client-utils.js
Signed-off-by: Vasil Petkov <v.petkov@sap.com>
=> Improve cf cmdline client to support '-c' option

test/broker/src/test/app-utils/src/index.js, test/broker/src/test/app-utils/test-app/app.js, test/broker/src/test/broker-acceptance-test.js, test/broker/src/test/broker-smoke-test.js
- fix problem in test app utils
- fix eslint issues
=> Fix broker smoke test

test/test-utils/src/index.js
- bump abacus submodule with minor fixes in cf acceptance test
- remove unused env variables from test utils
=> Update abacus submodule

test/broker/src/test/broker-acceptance-test.js, test/broker/src/test/broker-smoke-test.js
=> Refactorings in broker smoke test

lib/config/mappings/src/index.js
Signed-off-by: Vasil Petkov <v.petkov@sap.com>
=> Introduce edebug in mappings module

lib/extensions/healthchecker/src/index.js, lib/extensions/healthchecker/src/test/test.js, npm-shrinkwrap.json, package.json
- minor improvements in healthchecker tests
- add it to package.json to run its tests on build
=> Improvements in healthchecker

lib/cf/broker/src/routes/create-service.js, lib/plugins/provisioning/src/index.js, test/broker/src/test/app-utils/src/index.js, test/broker/src/test/app-utils/test-mapping-app/app.js, test/broker/src/test/app-utils/test-mapping-app/manifest.yml, test/broker/src/test/app-utils/test-mapping-app/package.json, test/broker/src/test/broker-acceptance-test.js, test/test-utils/src/index.js
Signed-off-by: Adriana Stefanova <adriana.stefanova@sap.com>
=> Add broker acceptance test for mapping api

scripts/bump-abacus.sh
Submodule abacus b1d9f58d..ab1b40a2:
> Rename get-usage script to get-report
> Implement configurable count window's granularity and size  in perf module (#780)
> Update batch README
> Update seqid README
> Add counters in reporting (#778)
> Update perf README
> Update README.md (#779)
> Name reporting variables (#775)
=> Bump Abacus

lib/cf/broker/npm-shrinkwrap.json, lib/cf/dashboard/.eslintignore, lib/cf/dashboard/npm-shrinkwrap.json, lib/cf/dashboard/package.json, lib/cf/dashboard/src/application.js, lib/cf/dashboard/src/middleware/authMiddleware.js, lib/cf/dashboard/src/test/authmiddleware-test.js, lib/cf/dashboard/src/test/frontend/karma.conf.js, lib/cf/dashboard/src/test/frontend/specs/httpInterceptor.spec.js, lib/cf/dashboard/src/test/routes-test.js, lib/cf/dashboard/src/utils/index.js, lib/cf/dashboard/src/utils/urlParser.js, lib/cf/dashboard/src/webapp/app.module.js, lib/cf/dashboard/src/webapp/components/factories/httpInterceptor.js, lib/cf/dashboard/src/webapp/dist/js/provider.js, lib/cf/dashboard/src/webapp/home.html, lib/extensions/healthchecker/npm-shrinkwrap.json, lib/extensions/housekeeper/npm-shrinkwrap.json, lib/plugins/account/npm-shrinkwrap.json, lib/plugins/provisioning/npm-shrinkwrap.json, npm-shrinkwrap.json
- Enable CSP for security tracking for dashboard
- Add more robust session management
- Add provision for logout handling
=> Add helmet for content security policy

lib/cf/broker/npm-shrinkwrap.json, lib/cf/dashboard/npm-shrinkwrap.json, lib/extensions/healthchecker/npm-shrinkwrap.json, lib/extensions/housekeeper/npm-shrinkwrap.json, lib/plugins/account/npm-shrinkwrap.json, lib/plugins/provisioning/npm-shrinkwrap.json, npm-shrinkwrap.json
Signed-off-by: Nikolay Maslarski <nikolay.maslarski@sap.com>
=> Update shrinkwrap files

tools/cmdline/src/test/test.js
=> Fix cmdline test

lib/plugins/provisioning/src/index.js, lib/plugins/provisioning/src/test/plan-mappings-test.js, lib/plugins/provisioning/src/test/plans-creation-test.js, lib/plugins/provisioning/src/test/plans-get-test.js, lib/plugins/provisioning/src/test/plans-updating-test.js, lib/plugins/provisioning/src/test/utils.js
=> Introduce resource specific scope authorization

test/provisioning/src/test/plans-acceptance-test.js
=> Fix plans acceptance test

lib/plugins/provisioning/src/index.js
=> Add error debug in provisioning plugin

lib/cf/broker/src/routes/update-service.js, lib/cf/broker/src/test/update-test.js, test/broker/src/test/broker-acceptance-test.js
=> Fix broker acceptance tests

tools/cmdline/src/cf-client-utils.js
Improve regex exp to work with cf cli v6.32 and v6.33
=> Change regex

tools/cmdline/src/cf-client-utils.js
=> change regex exp

lib/cf/broker/npm-shrinkwrap.json, lib/cf/dashboard/npm-shrinkwrap.json, lib/extensions/healthchecker/npm-shrinkwrap.json, lib/extensions/housekeeper/npm-shrinkwrap.json, lib/plugins/account/npm-shrinkwrap.json, lib/plugins/provisioning/npm-shrinkwrap.json, npm-shrinkwrap.json, package.json
=> Bump Abacus. Add http-status-codes to abacus-paging.

.envrc, .gitignore, lib/cf/broker/manifest.yml, lib/cf/broker/package.json, lib/cf/dashboard/.cfignore, lib/cf/dashboard/manifest.yml, lib/cf/dashboard/package.json, lib/extensions/healthchecker/manifest.yml, lib/extensions/healthchecker/package.json, lib/extensions/housekeeper/manifest.yml, lib/extensions/housekeeper/package.json, lib/plugins/account/manifest.yml, lib/plugins/account/package.json, lib/plugins/provisioning/manifest.yml, lib/plugins/provisioning/package.json, package.json
This reverts commit 919ca6196e88f66e332d96530cb7e398327b1590
=> Revert "Remove cf pack"

demo/java-demo-client/.gitignore, demo/java-demo-client/README.md, demo/java-demo-client/src/main/java/com/metering/cf/demo/util/NetworkHelper.java, demo/java-demo-client/src/main/java/com/metering/cf/demo/util/OAuthToken.java, demo/java-demo-client/src/main/webapp/App.js
* Switches to default plan with `sampleName` measyre
* Fixes OAuth token expiration logic
* Minor enhancements
=> fix(demo-app): correct plan and token code

test/broker/src/test/apps/test-app/app.js, test/broker/src/test/apps/test-app/manifest.yml, test/broker/src/test/apps/test-app/package.json
=> use abacus-request in broker smoke test app

package.json, yarn.lock
Signed-off-by: Adriana Stefanova <adriana.stefanova@sap.com>
=> Bump Abacus. Remove seconds, minutes and hours windows accumulation
